[package]
name = "discord_music_bot"
version = "1.0.0"
authors = ["Pentium1080Ti"]
edition = "2018"

[dependencies.serenity]
features = ["cache", "framework", "standard_framework", "voice", "http", "rustls_backend"]